export const TOP_100_MUNICIPALITIES = [
  "Brihanmumbai Municipal Corporation (BMC)",
  "Municipal Corporation of Delhi (MCD)",
  "Bruhat Bengaluru Mahanagara Palike (BBMP)",
  "Greater Hyderabad Municipal Corporation (GHMC)",
  "Ahmedabad Municipal Corporation (AMC)",
  "Greater Chennai Corporation (GCC)",
  "Kolkata Municipal Corporation (KMC)",
  "Surat Municipal Corporation (SMC)",
  "Pune Municipal Corporation (PMC)",
  "Jaipur Municipal Corporation (JMC)",
  "Lucknow Municipal Corporation (LMC)",
  "Kanpur Municipal Corporation (KMC)",
  "Nagpur Municipal Corporation (NMC)",
  "Indore Municipal Corporation (IMC)",
  "Thane Municipal Corporation (TMC)",
  "Bhopal Municipal Corporation (BMC)",
  "Visakhapatnam Greater Municipal Corporation (GVMC)",
  "Pimpri-Chinchwad Municipal Corporation (PCMC)",
  "Patna Municipal Corporation (PMC)",
  "Vadodara Municipal Corporation (VMC)",
  "Ghaziabad Municipal Corporation (GMC)",
  "Ludhiana Municipal Corporation (LMC)",
  "Agra Municipal Corporation (AMC)",
  "Nashik Municipal Corporation (NMC)",
  "Faridabad Municipal Corporation (FMC)",
  "Meerut Municipal Corporation (MMC)",
  "Rajkot Municipal Corporation (RMC)",
  "Kalyan-Dombivli Municipal Corporation (KDMC)",
  "Vasai-Virar City Municipal Corporation (VVCMC)",
  "Varanasi Municipal Corporation (VMC)",
  "Srinagar Municipal Corporation (SMC)",
  "Aurangabad Municipal Corporation (AMC)",
  "Dhanbad Municipal Corporation (DMC)",
  "Amritsar Municipal Corporation (AMC)",
  "Navi Mumbai Municipal Corporation (NMMC)",
  "Allahabad (Prayagraj) Municipal Corporation (PMC)",
  "Ranchi Municipal Corporation (RMC)",
  "Howrah Municipal Corporation (HMC)",
  "Coimbatore City Municipal Corporation (CCMC)",
  "Jabalpur Municipal Corporation (JMC)",
  "Gwalior Municipal Corporation (GMC)",
  "Vijayawada Municipal Corporation (VMC)",
  "Jodhpur Municipal Corporation (JMC)",
  "Madurai Corporation (MC)",
  "Raipur Municipal Corporation (RMC)",
  "Kota Municipal Corporation (KMC)",
  "Guwahati Municipal Corporation (GMC)",
  "Chandigarh Municipal Corporation (CMC)",
  "Solapur Municipal Corporation (SMC)",
  "Hubli-Dharwad Municipal Corporation (HDMC)",
  "Bareilly Municipal Corporation (BMC)",
  "Moradabad Municipal Corporation (MMC)",
  "Mysuru City Corporation (MCC)",
  "Gurugram Municipal Corporation (GMC)",
  "Aligarh Municipal Corporation (AMC)",
  "Jalandhar Municipal Corporation (JMC)",
  "Tiruchirappalli City Municipal Corporation (TCMC)",
  "Bhubaneswar Municipal Corporation (BMC)",
  "Salem City Municipal Corporation (SMC)",
  "Mira-Bhayandar Municipal Corporation (MBMC)",
  "Thiruvananthapuram Municipal Corporation (TMC)",
  "Bhiwandi-Nizampur City Municipal Corporation (BNCMC)",
  "Saharanpur Municipal Corporation (SMC)",
  "Gorakhpur Municipal Corporation (GMC)",
  "Guntur Municipal Corporation (GMC)",
  "Bikaner Municipal Corporation (BMC)",
  "Amravati Municipal Corporation (AMC)",
  "Noida Authority",
  "Jamshedpur Notified Area Committee (JNAC)",
  "Bhilai Municipal Corporation (BMC)",
  "Cuttack Municipal Corporation (CMC)",
  "Firozabad Municipal Corporation (FMC)",
  "Kochi Municipal Corporation (KMC)",
  "Bhavnagar Municipal Corporation (BMC)",
  "Dehradun Municipal Corporation (DMC)",
  "Durgapur Municipal Corporation (DMC)",
  "Asansol Municipal Corporation (AMC)",
  "Nanded-Waghala City Municipal Corporation (NWCMC)",
  "Kolhapur Municipal Corporation (KMC)",
  "Ajmer Municipal Corporation (AMC)",
  "Gulbarga City Corporation (GCC)",
  "Jamnagar Municipal Corporation (JMC)",
  "Ujjain Municipal Corporation (UMC)",
  "Loni Municipal Council",
  "Siliguri Municipal Corporation (SMC)",
  "Jhansi Municipal Corporation (JMC)",
  "Ulhasnagar Municipal Corporation (UMC)",
  "Nellore Municipal Corporation (NMC)",
  "Jammu Municipal Corporation (JMC)",
  "Sangli-Miraj-Kupwad City Municipal Corporation (SMKCMC)",
  "Belagavi City Corporation (BCC)",
  "Mangaluru City Corporation (MCC)",
  "Ambattur Municipality",
  "Tirunelveli City Municipal Corporation (TCMC)",
  "Malegaon Municipal Corporation (MMC)",
  "Gaya Municipal Corporation (GMC)",
  "Jalgaon Municipal Corporation (JMC)",
  "Udaipur Municipal Corporation (UMC)",
  "Maheshtala Municipality",
  "Tirupur City Municipal Corporation (TCMC)"
];
